### ISSUE TITLE
Operation not supported. Unknown error: 0x80004005.

### ISSUE THREAD

**Issue by duxa** [techl/MonoRemoteDebugger#10]
Could you help me with this error?

**Comment by techcap** [comment]
could you give me more detail and logs both?

**Comment by jesse-peters** [comment]
I'm getting the same error:

Operation not supported. Unknown error: 0x80004005.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MonoRemoteDebugger.VSExtension.MonoDebuggerPackage.<StartSearching>d__11.MoveNext()

**Comment by techcap** [comment]
Which OS and Mono version did you use for VS and target device?

**Comment by jesse-peters** [comment]
Visual studio 2015

We are using docker to build the image:

https://github.com/mono/docker

Looks like 4.2.3.4 is the latest version.

**Comment by techcap** [comment]
I dont know about docker. Which docker image did you use? I'll try to test with same environment.

**Comment by jesse-peters** [comment]
We're using the mono docker environment:https://github.com/mono/docker

Here is a quick dockerfile:
https://gist.github.com/syphon7/aa32df06f1d373c9e7fddbb0b32828e6

**Comment by jesse-peters** [comment]
Turned out to be a firewall issue. I needed to open ports: 13001, 11000 and 15000

**Comment by yasmoradi** [comment]
I'm going to debug my app on mono + Linux based docker using visual studio and this extension. Is this possible? Thanks anyway :)
