### ISSUE TITLE
The parameter is incorrect

### ISSUE THREAD

**Issue by packwoodm** [techl/MonoRemoteDebugger#17]
### Installed product versions
- Visual Studio: [2015 Community]
- This extension: [example 1.0.5]
### Description

Would really like to use this, but it doesn't work for me.  After starting remote debug server I get 'The parameter 'MyProject.csproj' is incorrect.'  Maybe a recipe for how to debug a simple app would help.
### Steps to recreate
1. Start remote debug server.
2. Select 'debug with mono (remote)'
3. Type IP address in the box
4. Get message box error
### Current behavior

I get an error instead of the debugger starting

2016-06-04 10:40:02.9134|ERROR|MonoRemoteDebugger.VSExtension.VSPackage|System.ArgumentException: The parameter 'Neuristics.Hrc.Import\Neuristics.Hrc.Import.csproj' is incorrect. ---> System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.SolutionClass.Item(Object index)
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.GetStartupProject()
   --- End of inner exception stack trace ---
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.GetStartupProject()
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.GetStartupAssemblyPath()
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MonoRemoteDebugger.VSExtension.VSPackage.<StartSearching>d__11.MoveNext()
### Expected behavior

According to the instructions the program will run and hit my breakpoint and I can enjoy debugging.

**Comment by techcap** [comment]
Could you check the mono version? I tested using v4.2.3.4.
And could you update MonoRemoteDebugger to v1.0.7?
If you still get the error after updating, could you send me the sample project?

**Comment by techcap** [comment]
Do you have problem still in v1.0.10?
