### ISSUE TITLE
Unable to start program

### ISSUE THREAD

**Issue by ccooper4** [techl/MonoRemoteDebugger#18]
### Installed product versions
- Visual Studio: [2015 Enterprise]
- This extension [v1.0.9]
### Description

Successfully connecting with my Raspberry Pi running mono but when executing the code I get a message saying \Documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\bin\Debug\ConsoleApplication1.exe cannot be found.  After checking this folder I can confirm the .exe file is there.  The application is just a simple hello world program to try and get MonoRemoteDebugger working.
### Steps to recreate

1) Create a new console application in VS
2) Click debug with mono (remote)
3) Select my pi's IP address

**Comment by techcap** [comment]
What is your mono version? I tested on mono 4.2.3.4 with raspberry pi.

**Comment by ccooper4** [comment]
Mono version:  Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:34:50 UTC 2016)

### The log file contains the following information after trying a remote build:

2016-06-13 18:03:28.7096|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7Engine (entering) :  SetRegistryRoot
2016-06-13 18:03:28.7096|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7Engine (entering) :  SetLocale
2016-06-13 18:03:28.7096|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7Engine (entering) :  LaunchSuspended
2016-06-13 18:03:28.7096|ERROR|MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension|System.Runtime.InteropServices.COMException (0x89710016): Unable to start program 'C:\Users\ccoop\Documents\Visual Studio 2015\Projects\SimpleMarketApp\SimpleMarketApp\bin\Debug\SimpleMarketApp.exe'.

The system cannot find the file specified.

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
2016-06-13 18:03:28.7096|ERROR|MonoRemoteDebugger.VSExtension.VSPackage|System.Runtime.InteropServices.COMException (0x89710016): Unable to start program 'C:\Users\ccoop\Documents\Visual Studio 2015\Projects\SimpleMarketApp\SimpleMarketApp\bin\Debug\SimpleMarketApp.exe'.

The system cannot find the file specified.

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MonoRemoteDebugger.VSExtension.VSPackage.<StartSearching>d__11.MoveNext()

I have tried running the project from the desktop too but unfortunately I am getting the same error 'The system cannot find the file specified'

I will try a clean install of VS15 and reinstalling the MonoRemoteDebugger extension.

**Comment by robert44** [comment]
I have the same problem, version 1.0.7 still worked for me.

The problem is on the plugin side, I can connect to a 1.0.9 server with the 1.0.7 plugin.
Looks like it has to do with the reference change on 6/6/2016 from Mono.Cecil to Xamarin.VisualStudio.Cecil

Mono version on target is 4.2.3.4
VS2015 Pro / 14.0.25123.00 Update 2 / Xamarin 4.1.0.530

**Comment by simonegli8** [comment]
Same problem here. Mono Version 4.4, Windows 10 Pro. The Problem is also in my Fork **[MonoTools](http://github.com/simonegli8/MonoTools)**

**Comment by techcap** [comment]
Fixed the bug in v1.0.10.
Changed mono related dlls with custom build.
