### ISSUE TITLE
HRESULT: Ox80070057 (E INVALIDARG)

### ISSUE THREAD

**Issue by alandixon** [techl/MonoRemoteDebugger#4]
I start the remote (Linux) MonoRemoteDebugger.Server as root.
In the local VS2013, I select Debug with Mono (remote)
I enter the remote IP address and click [Connect]
Within about 1 second (on one occasion 30 seconds), I get an error dialog that says

MonoRemoteDebugger
The parameter is incorrect. (Exception from HRESULT: Ox80070057 (E_INVALIDARG)) 

The remote end does not indicate that anything has happened.
No other clue as to what is wrong.

Local: Windows 7 Prof, VS2013, MonoRemoteDebugger v0.2
Remote: Linux Mint 17.3, MonoRemoteDebugger.Server v1.0.2

Thanks,
Alan

**Comment by alandixon** [comment]
Bit more info from the log that I forgot yesterday:
(fwiw, I don't think there's any problem with the startup project).
`2016-02-04 14:27:38.9981|ERROR|MonoRemoteDebugger.VSExtension.MonoDebuggerPackage|System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.SolutionClass.Item(Object index)
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.GetStartupProject()
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.GetStartupAssemblyPath()
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MonoRemoteDebugger.VSExtension.MonoDebuggerPackage.<StartSearching>d__11.MoveNext()`

**Comment by PapaMufflon** [comment]
I have the same error and the failure is that when the startup project is inside a solution folder, it is not working. Move it to the top level and it works.

**Comment by techcap** [comment]
Fixed at v1.0.9.
