### ISSUE TITLE
Can't get it to work -- Installed as per instructions

### ISSUE THREAD

**Issue by ghost** [techl/MonoRemoteDebugger#43]
### Installed product versions
- Visual Studio: 2017 
- This extension: [example 1.1.21]

### Description
Replace this text with a short description

### Steps to recreate
1. Try to RemoteDebug

### Current behavior PC SIDE
2018-01-22 14:34:13.7355|ERROR|MonoRemoteDebugger.SharedLib.TcpCommunication|ReceiveContent(0) failed!
2018-01-22 14:34:13.7355|INFO|MonoRemoteDebugger.SharedLib.Server.ClientSession|Null-Message received
2018-01-22 14:34:13.7355|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Waiting for client
2018-01-22 14:34:13.7475|ERROR|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.Stop()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

2018-01-22 14:34:13.7475|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Closed MonoDebugServer
2018-01-22 14:34:13.7595|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7ProgramProvider (entering) :  WatchForProviderEvents
2018-01-22 14:35:10.7099|ERROR|MonoRemoteDebugger.VSExtension.VSPackage|System.Exception: Did not receive an answer in time...
   at MonoRemoteDebugger.VSExtension.MonoClient.DebugSession.<WaitForAnswerAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoRemoteDebugger.VSExtension.VSPackage.<StartSearching>d__11.MoveNext()

### BB Side
2018-01-22 01:33:57.5571|TRACE|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Start announcing
2018-01-22 01:33:57.9819|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Waiting for client
2018-01-22 01:34:51.4763|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Accepted client: 192.168.100.153:52029
2018-01-22 01:34:51.9963|TRACE|MonoRemoteDebugger.SharedLib.Server.ClientSession|New Session from 192.168.100.153
2018-01-22 01:34:52.1413|ERROR|MonoRemoteDebugger.SharedLib.Server.ClientSession|System.Runtime.Serialization.SerializationException: Enum value 'DebugLastContent' is invalid for type 'MonoRemoteDebugger.SharedLib.Command' and cannot be deserialized.
  at System.Runtime.Serialization.EnumMap.DeserializeContent (System.Xml.XmlReader reader, System.Runtime.Serialization.XmlFormatterDeserializer deserializer, System.String id) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.SerializationMap.DeserializeObject (System.Xml.XmlReader reader, System.Runtime.Serialization.XmlFormatterDeserializer deserializer) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.XmlFormatterDeserializer.DeserializeByMap (System.Xml.XmlQualifiedName name, System.Type type, System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.XmlFormatterDeserializer.Deserialize (System.Type type, System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.SerializationMap.DeserializeContent (System.Xml.XmlReader reader, System.Runtime.Serialization.XmlFormatterDeserializer deserializer, System.String id, Boolean empty) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.SerializationMap.DeserializeContent (System.Xml.XmlReader reader, System.Runtime.Serialization.XmlFormatterDeserializer deserializer, System.String id) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.SerializationMap.DeserializeObject (System.Xml.XmlReader reader, System.Runtime.Serialization.XmlFormatterDeserializer deserializer) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.XmlFormatterDeserializer.DeserializeByMap (System.Xml.XmlQualifiedName name, System.Type type, System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.XmlFormatterDeserializer.Deserialize (System.Type type, System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.XmlFormatterDeserializer.Deserialize (System.Xml.XmlReader reader, System.Type declaredType, System.Runtime.Serialization.KnownTypeCollection knownTypes, IDataContractSurrogate surrogate, System.Runtime.Serialization.DataContractResolver resolver, System.Runtime.Serialization.DataContractResolver defaultResolver, System.String name, System.String ns, Boolean verifyObjectName) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.DataContractSerializer.ReadObject (System.Xml.XmlDictionaryReader reader, Boolean verifyObjectName) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.XmlObjectSerializer.ReadObject (System.Xml.XmlDictionaryReader reader) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.DataContractSerializer.ReadObject (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Runtime.Serialization.XmlObjectSerializer.ReadObject (System.IO.Stream stream) [0x00000] in <filename unknown>:0
  at MonoRemoteDebugger.SharedLib.TcpCommunication.ReceiveContent (Int32 size) [0x00000] in <filename unknown>:0
  at MonoRemoteDebugger.SharedLib.TcpCommunication.Receive () [0x00000] in <filename unknown>:0
  at MonoRemoteDebugger.SharedLib.Server.ClientSession.HandleSession () [0x00000] in <filename unknown>:0

### Expected behavior
Explain what it should be doing after it's fixed.  I will work?

**Comment by techcap** [comment]
Did you try to use v1.3.0?

**Comment by ghost** [comment]
Strangely, all is working well now. I cant explain the error.

Kindest Regards
David Shields


*David Shields*
*Mobile: +64275403356*
*Country: New Zealand*
