### ISSUE TITLE
Compressed or Uncompressed size, or offset exceeds the maximum value

### ISSUE THREAD

**Issue by TaoVonQi** [techl/MonoRemoteDebugger#49]
Can you please help?? I'm getting this issue and I don't know how I can fix it!

### Installed product versions
- Visual Studio: [2017 enterprise]
- This extension: [1.3.0]

### Description
ERROR|MonoRemoteDebugger.VSExtension.VSPackage|Ionic.Zip.ZipException: Compressed or Uncompressed size, or offset exceeds the maximum value. Consider setting the UseZip64WhenSaving property on the ZipFile instance.
   at Ionic.Zip.ZipEntry.SetZip64Flags()
   at Ionic.Zip.ZipEntry.PostProcessOutput(Stream s)
   at Ionic.Zip.ZipEntry._WriteEntryData(Stream s)
   at Ionic.Zip.ZipEntry.Write(Stream s)
   at Ionic.Zip.ZipFile.Save()
   at Ionic.Zip.ZipFile.Save(String fileName)
   at MonoRemoteDebugger.SharedLib.ZipFile.CreateFromDirectory(String directory, String targetZip)
   at MonoRemoteDebugger.VSExtension.MonoClient.DebugSession.TransferFiles()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoRemoteDebugger.VSExtension.VSPackage.<StartSearching>d__11.MoveNext()

Is there a way to set this "UseZip64WhenSaving" property?

**Comment by TaoVonQi** [comment]
I believe it should be fixed by adding the following line in ZipFile.cs:

 zip.UseZip64WhenSaving = Zip64Option.AsNecessary;

**Comment by techcap** [comment]
Could you make PR for this?

**Comment by techcap** [comment]
published v1.4.0
